### ISSUE TITLE
Segfault while downloading many files at the same time

### ISSUE THREAD

**Issue by whirm** [libswift/libswift#52]
```
└──> gdb --core=/tmp/core.5 swift
GNU gdb (Debian 7.7.1+dfsg-3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from swift...(no debugging symbols found)...done.
[New LWP 13582]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/var/data/feina/code/delft/tribler/swift -j -l 0.0.0.0:10970 -c 127.0.0.1:11379'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  evbuffer_add_buffer (outbuf=0x0, inbuf=0x1c22820) at buffer.c:865
865 buffer.c: No such file or directory.
(gdb) bt
#0  evbuffer_add_buffer (outbuf=0x0, inbuf=0x1c22820) at buffer.c:865
#1  0x000000000042cfd0 in CmdGwDataCameInCallback(bufferevent*, void*) ()
#2  0x00007f7471b1db6a in bufferevent_readcb (fd=0xc, event=<optimized out>, arg=0xeb8ff0) at bufferevent_sock.c:186
#3  0x00007f7471b13184 in event_process_active_single_queue (activeq=0xea6fb0, base=0xea6b70) at event.c:1350
#4  event_process_active (base=<optimized out>) at event.c:1420
#5  event_base_loop (base=0xea6b70, flags=0x0) at event.c:1621
#6  0x0000000000409185 in utf8main(int, char**) ()
#7  0x000000000040ca01 in main ()
```

**Comment by LipuFei** [comment]
@badrock This should be fixed by #52.
